- name: Prerequisites
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Create output directory {{ OUTPUT_DIRECTORY }}
      file:
        path: "{{ OUTPUT_DIRECTORY }}"
        state: directory
        recurse: yes
        mode: 0777
- name: Get GFS data
  hosts: all
  strategy: free
  tasks:
    - name: Set GFS files start date and number of downloads
      set_fact:
        gfsDay: "{{START_DATE[:8]}}"
        gfsHour: "{{START_DATE[8:]}}"
        nbHours: "{{ (END_DATE|int) - (START_DATE|int) }}"
    - name: Download GFS analysis of initial atmospheric conditions file
      get_url:
        url: "https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t12z.pgrb2.0p25.anl&subregion=&leftlon={{ LEFT_LONGITUDE }}&rightlon={{ RIGHT_LONGITUDE }}&toplat={{ TOP_LATITUDE }}&bottomlat={{ BOTTOM_LATITUDE }}&dir=%2Fgfs.{{ gfsDay }}%2F{{ gfsHour }}"
        dest: "{{ OUTPUT_DIRECTORY }}"
        mode: 0755
    - name: Download GFS data files for each hour
      get_url:
        url: "https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file={{ item }}&subregion=&leftlon={{ LEFT_LONGITUDE }}&rightlon={{ RIGHT_LONGITUDE }}&toplat={{ TOP_LATITUDE }}&bottomlat={{ BOTTOM_LATITUDE }}&dir=%2Fgfs.{{ gfsDay }}%2F{{ gfsHour }}"
        dest: "{{ OUTPUT_DIRECTORY }}/{{ item }}.grb"
        mode: 0755
      with_sequence: start=0 end={{nbHours|int}} format=gfs.t12z.pgrb2.0p25.f0%02d
