- name: Prequisites
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Ubuntu - install unzip and bzip2 (acl needed by Ansible to become an unprivileged user)
      apt:
        name:
          - acl
          - unzip
          - bzip2
        state: present
        update_cache: yes
      register: apt_res
      retries: 3
      until: apt_res is success
      when: ansible_distribution == 'Ubuntu'
    - name: RedHat - install unzip and bzip2
      yum:
        name:
          - unzip
          - bzip2
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'
    - name: Debian - install unzip and bzip2
      apt:
        name:
          - unzip
          - bzip2
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Create output directory
      file:
        path: "{{ OUTPUT_DIRECTORY }}"
        state: directory
        recurse: yes
        mode: 0777

- name: Get GEOG data
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Download GEOG data
      get_url:
        url: "https://www2.mmm.ucar.edu/wrf/src/wps_files/geog_high_res_mandatory.tar.gz"
        dest: "{{ OUTPUT_DIRECTORY }}"
        validate_certs: no
        mode: 0755
    - name: Extract archive
      unarchive:
        src: "{{ OUTPUT_DIRECTORY }}/geog_high_res_mandatory.tar.gz"
        dest: "{{ OUTPUT_DIRECTORY }}"
        remote_src: yes
    - name: Remove archive
      file:
        path: "{{ OUTPUT_DIRECTORY }}/geog_high_res_mandatory.tar.gz"
        state: absent
- name: Get additional data
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  vars:
    geog_files:
      - albedo_modis.tar.bz2
      - maxsnowalb_modis.tar.bz2
      - modis_landuse_21class_30s.tar.bz2
      - lake_depth.tar.bz2
      - NUDAPT44_1km.tar.bz2
      - urbfrac_nlcd2011.tar.bz2
      - nlcd2011_imp_ll_9s.tar.bz2
      - nlcd2011_can_ll_9s.tar.bz2
      - erod.tar.bz2
      - clayfrac_5m.tar.bz2
      - sandfrac_5m.tar.bz2
  tasks:
    - name: Download GEOG data
      get_url:
        url: "https://www2.mmm.ucar.edu/wrf/src/wps_files/{{ item }}"
        dest: "{{ OUTPUT_DIRECTORY }}"
        validate_certs: no
        mode: 0755
      with_items: "{{ geog_files }}"
    - name: Extract archive
      unarchive:
        src: "{{ OUTPUT_DIRECTORY }}/{{ item }}"
        dest: "{{ OUTPUT_DIRECTORY }}/WPS_GEOG/"
        remote_src: yes
      with_items: "{{ geog_files }}"
    - name: Remove archive
      file:
        path: "{{ OUTPUT_DIRECTORY }}/{{ item }}"
        state: absent
      with_items: "{{ geog_files }}"
