- name: Delete directories
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Get list of directories to delete
      set_fact:
        directories: "{{dirs_to_delete | from_json}}"
    - name: Delete directories
      file:
        # accepted input for containers: volumes with format path:mountpoint
        # in which case, only the first element has to be deleted
        path: "{{ item.split(':')[0] }}"
        state: absent
      loop: "{{ directories }}"
