- name: Move the content of a source directory to staging area
  hosts: all
  strategy: free
  become: true
  become_user: "{{ user_name }}"
  become_method: sudo
  tasks:
    - name: Get destination directory
      set_fact:
        DIRECTORY_ABSOLUTE_PATH: "{{ destination_directory }}/{{ destination_subdirectory }}"
    - name: "Create destination directory {{ DIRECTORY_ABSOLUTE_PATH }}"
      file:
        path: "{{ DIRECTORY_ABSOLUTE_PATH }}"
        state: directory
        recurse: yes
        mode: 0744
    - name: "Get source files to copy"
      set_fact:
        patterns: "{{ source_files | from_json }}"
    - name: "Copying source directory {{ source_directory }} content to staging area"
      shell: "/bin/mv {{ source_directory }}/* {{ DIRECTORY_ABSOLUTE_PATH }}"
      when: patterns | length == 0
    - name: "Copying source files to staging area"
      shell: "/bin/mv {{ source_directory }}/{{ item }} {{ DIRECTORY_ABSOLUTE_PATH }}"
      with_items: "{{ patterns }}"
      when: patterns | length > 0
