- name: Moving file
  hosts: all
  strategy: free
  tasks:
    - name: "Moving file as default user"
      shell: "mv  {{ source_file }} {{ destination }}"
      when: as_user == ""
    - name: "Moving file "
      shell: "mv  {{ source_file }} {{ destination }}"
      become_user: "{{ as_user }}"
      become: true
      become_method: sudo
      when: as_user != ""
    - name: "Update permissions"
      file:
        path: "{{ destination }}"
        recurse: yes
        mode: 0777
      become: true
      become_method: sudo
      when: as_user != ""
