- name: "Creating script"
  hosts: all
  strategy: linear
  tasks:
    - name: Create script
      copy:
        content: "{{ SCRIPT_CONTENT }}"
        dest: "/tmp/lexis_exec_script.sh"
        mode: 0555
