- name: ADMS run
  hosts: all
  strategy: free
  tasks:
    - name: Create ADMS script
      template:
        src: adms_runner.ps1.j2
        dest: "{{ansible_env.HOME}}\\adms_runner.ps1"
        mode: "u=rwx,g=rwx,o=r"
    - name: Run script
      raw: "{{ansible_env.HOME}}\\adms_runner.ps1"
      register: result
    - debug: var=result.stdout
